services:
  mysql:
    image: mysql:8.0.35
    container_name: social-login-mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      TZ: Asia/Seoul
      MYSQL_DATABASE: social-login
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data: