services:
  springboot-gwana:
    container_name: springboot-gwana-container
    image: springboot-gwana:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:log4jdbc:mysql://mysql-gwana:3306/social-login?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=!
    networks:
      - gwana-network
    depends_on:
      mysql-gwana:
        condition: service_healthy

  mysql-gwana:
    container_name: mysql-gwana
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: H/KMC1029ys!
      MYSQL_DATABASE: social-login
      MYSQL_USER: myuser
      MYSQL_PASSWORD: H/KMC1029ys!
    ports:
      - "3306:3306"
    networks:
      - gwana-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

networks:
  gwana-network:
    driver: bridge